### ISSUE TITLE
BRCA Exchange API

### ISSUE THREAD

**Issue by david4096** [labbcb/GA4GHclient#23]
We have a third implementation of the GA4GH API for the BRCA exchange data [here](http://brcaexchange.org/about/api). Here is the repo if you find issues! https://github.com/BD2KGenomics/brca-exchange/issues

`http post http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search referenceName=17 start=41191616 end=41191617 variantSetId=brca-hg37`

**Comment by Welliton309** [comment]
Thank you @david4096 for sharing this implementation. I tried to use the GA4GHclient package for searching variants and it worked very well. Here is a simple example:

``` r
library(GA4GHclient)
host <- "http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/"
datasetList <- searchDatasets(host)
datasetId <- datasetList$datasets$id[1]
variantSetList <- searchVariantSets(host, datasetId)
variantSetId <- variantSetList$variantSets$id[2]
variants <- searchVariants(host, variantSetId, referenceName = "chr17", start = 41246794, end = 41296814, pageSize = 100, full = TRUE)
nrow(variants$variants)
```

It will return 364 variants present in BRCA exchange data server.
